package com.example.gacha_fit.base_datos;

import java.util.HashMap;
import java.util.Map;

public class DatosEjercicios {

    public static Map<String, Object>[] obtenerEjercicios() {
        //Lista con todos los ejercicios que se introduciran a la base de datos.
        //Esta hecho de esta forma para poder actualizar la base de datos de una forma más rápida.
        Map<String, Object>[] ejercicios = new Map[30];

        Map<String, Object> ejercicio1 = new HashMap<>();
        ejercicio1.put("nombre", "Curl de bíceps");
        ejercicio1.put("descripcion", "Ejercicio clásico con mancuernas para trabajar los bíceps.");
        ejercicio1.put("dificultad_facil", "10");
        ejercicio1.put("dificultad_normal", "15");
        ejercicio1.put("dificultad_dificil", "20");
        ejercicio1.put("medida","reps");
        ejercicio1.put("puntuacion_facil", 5);
        ejercicio1.put("puntuacion_normal", 10);
        ejercicio1.put("puntuacion_dificil", 15);
        ejercicio1.put("tipo", "brazo");
        ejercicio1.put("imagen_url", "curl_biceps");
        ejercicio1.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[0] = ejercicio1;

        Map<String, Object> ejercicio2 = new HashMap<>();
        ejercicio2.put("nombre", "Flexiones diamante");
        ejercicio2.put("descripcion", "Flexiones con manos juntas en forma de diamante para tríceps.");
        ejercicio2.put("dificultad_facil", "20");
        ejercicio2.put("dificultad_normal", "30");
        ejercicio2.put("dificultad_dificil", "45");
        ejercicio2.put("medida","seg");
        ejercicio2.put("puntuacion_facil", 6);
        ejercicio2.put("puntuacion_normal", 11);
        ejercicio2.put("puntuacion_dificil", 16);
        ejercicio2.put("tipo", "brazo");
        ejercicio2.put("imagen_url", "flexiones_diamante");
        ejercicio2.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[1] = ejercicio2;

        Map<String, Object> ejercicio3 = new HashMap<>();
        ejercicio3.put("nombre", "Fondos en banco");
        ejercicio3.put("descripcion", "Tríceps sobre un banco, bajando y subiendo el cuerpo.");
        ejercicio3.put("dificultad_facil", "10");
        ejercicio3.put("dificultad_normal", "15");
        ejercicio3.put("dificultad_dificil", "20");
        ejercicio3.put("medida","reps");
        ejercicio3.put("puntuacion_facil", 5);
        ejercicio3.put("puntuacion_normal", 10);
        ejercicio3.put("puntuacion_dificil", 15);
        ejercicio3.put("tipo", "brazo");
        ejercicio3.put("imagen_url", "fondos_banco");
        ejercicio3.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[2] = ejercicio3;

        Map<String, Object> ejercicio4 = new HashMap<>();
        ejercicio4.put("nombre", "Martillo con mancuerna");
        ejercicio4.put("descripcion", "Similar al curl, pero con agarre neutro.");
        ejercicio4.put("dificultad_facil", "10");
        ejercicio4.put("dificultad_normal", "15");
        ejercicio4.put("dificultad_dificil", "20");
        ejercicio4.put("medida","reps");
        ejercicio4.put("puntuacion_facil", 5);
        ejercicio4.put("puntuacion_normal", 10);
        ejercicio4.put("puntuacion_dificil", 15);
        ejercicio4.put("tipo", "brazo");
        ejercicio4.put("imagen_url", "martillo");
        ejercicio4.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[3] = ejercicio4;

        Map<String, Object> ejercicio5 = new HashMap<>();
        ejercicio5.put("nombre", "Círculos de brazos");
        ejercicio5.put("descripcion", "Extiende los brazos y haz círculos.");
        ejercicio5.put("dificultad_facil", "30");
        ejercicio5.put("dificultad_normal", "45");
        ejercicio5.put("dificultad_dificil", "60");
        ejercicio5.put("medida","seg");
        ejercicio5.put("puntuacion_facil", 4);
        ejercicio5.put("puntuacion_normal", 8);
        ejercicio5.put("puntuacion_dificil", 12);
        ejercicio5.put("tipo", "brazo");
        ejercicio5.put("imagen_url", "circulos_brazos");
        ejercicio5.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[4] = ejercicio5;

        Map<String, Object> ejercicio6 = new HashMap<>();
        ejercicio6.put("nombre", "Press militar");
        ejercicio6.put("descripcion", "Empuja pesas por encima de la cabeza.");
        ejercicio6.put("dificultad_facil", "8");
        ejercicio6.put("dificultad_normal", "12");
        ejercicio6.put("dificultad_dificil", "15");
        ejercicio6.put("medida","reps");
        ejercicio6.put("puntuacion_facil", 5);
        ejercicio6.put("puntuacion_normal", 10);
        ejercicio6.put("puntuacion_dificil", 15);
        ejercicio6.put("tipo", "brazo");
        ejercicio6.put("imagen_url", "press_militar");
        ejercicio6.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[5] = ejercicio6;

        Map<String, Object> ejercicio7 = new HashMap<>();
        ejercicio7.put("nombre", "Elevaciones laterales");
        ejercicio7.put("descripcion", "Eleva los brazos hacia los lados.");
        ejercicio7.put("dificultad_facil", "10");
        ejercicio7.put("dificultad_normal", "15");
        ejercicio7.put("dificultad_dificil", "20");
        ejercicio7.put("medida","reps");
        ejercicio7.put("puntuacion_facil", 5);
        ejercicio7.put("puntuacion_normal", 10);
        ejercicio7.put("puntuacion_dificil", 15);
        ejercicio7.put("tipo", "brazo");
        ejercicio7.put("imagen_url", "elevaciones_laterales");
        ejercicio7.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[6] = ejercicio7;

        Map<String, Object> ejercicio8 = new HashMap<>();
        ejercicio8.put("nombre", "Extensión de tríceps");
        ejercicio8.put("descripcion", "Extiende el antebrazo desde detrás de la cabeza.");
        ejercicio8.put("dificultad_facil", "8");
        ejercicio8.put("dificultad_normal", "12");
        ejercicio8.put("dificultad_dificil", "15");
        ejercicio8.put("medida","reps");
        ejercicio8.put("puntuacion_facil", 5);
        ejercicio8.put("puntuacion_normal", 10);
        ejercicio8.put("puntuacion_dificil", 15);
        ejercicio8.put("tipo", "brazo");
        ejercicio8.put("imagen_url", "extension_triceps");
        ejercicio8.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[7] = ejercicio8;

        Map<String, Object> ejercicio9 = new HashMap<>();
        ejercicio9.put("nombre", "Flexiones a una mano");
        ejercicio9.put("descripcion", "Flexiones con una mano.");
        ejercicio9.put("dificultad_facil", "5");
        ejercicio9.put("dificultad_normal", "8");
        ejercicio9.put("dificultad_dificil", "10");
        ejercicio9.put("medida","reps");
        ejercicio9.put("puntuacion_facil", 6);
        ejercicio9.put("puntuacion_normal", 12);
        ejercicio9.put("puntuacion_dificil", 18);
        ejercicio9.put("tipo", "brazo");
        ejercicio9.put("imagen_url", "flexion_una_mano");
        ejercicio9.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[8] = ejercicio9;

        Map<String, Object> ejercicio10 = new HashMap<>();
        ejercicio10.put("nombre", "Plancha con toque de hombros");
        ejercicio10.put("descripcion", "Toca el hombro opuesto desde plancha.");
        ejercicio10.put("dificultad_facil", "30");
        ejercicio10.put("dificultad_normal", "45");
        ejercicio10.put("dificultad_dificil", "60");
        ejercicio10.put("medida","seg");
        ejercicio10.put("puntuacion_facil", 4);
        ejercicio10.put("puntuacion_normal", 8);
        ejercicio10.put("puntuacion_dificil", 12);
        ejercicio10.put("tipo", "brazo");
        ejercicio10.put("imagen_url", "toque_hombros");
        ejercicio10.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[9] = ejercicio10;

        Map<String, Object> ejercicio11 = new HashMap<>();
        ejercicio11.put("nombre", "Sentadillas");
        ejercicio11.put("descripcion", "Ejercicio fundamental para piernas y glúteos.");
        ejercicio11.put("dificultad_facil", "15");
        ejercicio11.put("dificultad_normal", "20");
        ejercicio11.put("dificultad_dificil", "25");
        ejercicio11.put("medida","reps");
        ejercicio11.put("puntuacion_facil", 5);
        ejercicio11.put("puntuacion_normal", 10);
        ejercicio11.put("puntuacion_dificil", 15);
        ejercicio11.put("tipo", "pierna");
        ejercicio11.put("imagen_url", "sentadillas");
        ejercicio11.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[10] = ejercicio11;

        Map<String, Object> ejercicio12 = new HashMap<>();
        ejercicio12.put("nombre", "Zancadas");
        ejercicio12.put("descripcion", "Paso largo hacia adelante, bajando la rodilla trasera. Las repeticiones son por pierna.");
        ejercicio12.put("dificultad_facil", "10");
        ejercicio12.put("dificultad_normal", "15");
        ejercicio12.put("dificultad_dificil", "20");
        ejercicio12.put("medida","reps");
        ejercicio12.put("puntuacion_facil", 6);
        ejercicio12.put("puntuacion_normal", 11);
        ejercicio12.put("puntuacion_dificil", 16);
        ejercicio12.put("tipo", "pierna");
        ejercicio12.put("imagen_url", "zancadas");
        ejercicio12.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[11] = ejercicio12;

        Map<String, Object> ejercicio13 = new HashMap<>();
        ejercicio13.put("nombre", "Puente glúteo");
        ejercicio13.put("descripcion", "Levanta la cadera desde el suelo.");
        ejercicio13.put("dificultad_facil", "15");
        ejercicio13.put("dificultad_normal", "20");
        ejercicio13.put("dificultad_dificil", "25");
        ejercicio13.put("medida","reps");
        ejercicio13.put("puntuacion_facil", 5);
        ejercicio13.put("puntuacion_normal", 10);
        ejercicio13.put("puntuacion_dificil", 15);
        ejercicio13.put("tipo", "pierna");
        ejercicio13.put("imagen_url", "puente_gluteo");
        ejercicio13.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[12] = ejercicio13;

        Map<String, Object> ejercicio14 = new HashMap<>();
        ejercicio14.put("nombre", "Sentadilla sumo");
        ejercicio14.put("descripcion", "Sentadilla con piernas abiertas.");
        ejercicio14.put("dificultad_facil", "12");
        ejercicio14.put("dificultad_normal", "18");
        ejercicio14.put("dificultad_dificil", "24");
        ejercicio14.put("medida","reps");
        ejercicio14.put("puntuacion_facil", 5);
        ejercicio14.put("puntuacion_normal", 10);
        ejercicio14.put("puntuacion_dificil", 15);
        ejercicio14.put("tipo", "pierna");
        ejercicio14.put("imagen_url", "sentadilla_sumo");
        ejercicio14.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[13] = ejercicio14;

        Map<String, Object> ejercicio15 = new HashMap<>();
        ejercicio15.put("nombre", "Sentadilla búlgara");
        ejercicio15.put("descripcion", "Apoya una pierna sobre un banco detrás de ti y realiza una sentadilla con la pierna delantera. Las repeticiones son por pierna.");
        ejercicio15.put("dificultad_facil", "8");
        ejercicio15.put("dificultad_normal", "12");
        ejercicio15.put("dificultad_dificil", "15");
        ejercicio15.put("medida","reps");
        ejercicio15.put("puntuacion_facil", 6);
        ejercicio15.put("puntuacion_normal", 11);
        ejercicio15.put("puntuacion_dificil", 16);
        ejercicio15.put("tipo", "pierna");
        ejercicio15.put("imagen_url", "bulgaras");
        ejercicio15.put("video", "https://www.youtube.com/watch?v=2C-uNgKwPLE");
        ejercicios[14] = ejercicio15;

        Map<String, Object> ejercicio16 = new HashMap<>();
        ejercicio16.put("nombre", "Jump Squats");
        ejercicio16.put("descripcion", "Sentadilla con salto.");
        ejercicio16.put("dificultad_facil", "10");
        ejercicio16.put("dificultad_normal", "15");
        ejercicio16.put("dificultad_dificil", "20");
        ejercicio16.put("medida","reps");
        ejercicio16.put("puntuacion_facil", 6);
        ejercicio16.put("puntuacion_normal", 11);
        ejercicio16.put("puntuacion_dificil", 16);
        ejercicio16.put("tipo", "pierna");
        ejercicio16.put("imagen_url", "jump_squats");
        ejercicio16.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[15] = ejercicio16;

        Map<String, Object> ejercicio17 = new HashMap<>();
        ejercicio17.put("nombre", "Elevación de talones");
        ejercicio17.put("descripcion", "Para fortalecer pantorrillas.");
        ejercicio17.put("dificultad_facil", "15");
        ejercicio17.put("dificultad_normal", "20");
        ejercicio17.put("dificultad_dificil", "25");
        ejercicio17.put("medida","reps");
        ejercicio17.put("puntuacion_facil", 5);
        ejercicio17.put("puntuacion_normal", 10);
        ejercicio17.put("puntuacion_dificil", 15);
        ejercicio17.put("tipo", "pierna");
        ejercicio17.put("imagen_url", "elevacion_talones");
        ejercicio17.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[16] = ejercicio17;

        Map<String, Object> ejercicio18 = new HashMap<>();
        ejercicio18.put("nombre", "Peso muerto");
        ejercicio18.put("descripcion", "Con peso, baja y sube con la espalda recta.");
        ejercicio18.put("dificultad_facil", "10");
        ejercicio18.put("dificultad_normal", "15");
        ejercicio18.put("dificultad_dificil", "20");
        ejercicio18.put("medida","reps");
        ejercicio18.put("puntuacion_facil", 5);
        ejercicio18.put("puntuacion_normal", 10);
        ejercicio18.put("puntuacion_dificil", 15);
        ejercicio18.put("tipo", "pierna");
        ejercicio18.put("imagen_url", "peso_muerto");
        ejercicio18.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[17] = ejercicio18;

        Map<String, Object> ejercicio19 = new HashMap<>();
        ejercicio19.put("nombre", "Step lateral");
        ejercicio19.put("descripcion", "Paso lateral sobre plataforma. Las repeticiones son por pierna.");
        ejercicio19.put("dificultad_facil", "10");
        ejercicio19.put("dificultad_normal", "15");
        ejercicio19.put("dificultad_dificil", "20");
        ejercicio19.put("medida","reps");
        ejercicio19.put("puntuacion_facil", 5);
        ejercicio19.put("puntuacion_normal", 10);
        ejercicio19.put("puntuacion_dificil", 15);
        ejercicio19.put("tipo", "pierna");
        ejercicio19.put("imagen_url", "step_lateral");
        ejercicio19.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[18] = ejercicio19;

        Map<String, Object> ejercicio20 = new HashMap<>();
        ejercicio20.put("nombre", "Escaladores");
        ejercicio20.put("descripcion", "Lleva las rodillas al pecho desde plancha.");
        ejercicio20.put("dificultad_facil", "30");
        ejercicio20.put("dificultad_normal", "45");
        ejercicio20.put("dificultad_dificil", "60");
        ejercicio20.put("medida","seg");
        ejercicio20.put("puntuacion_facil", 4);
        ejercicio20.put("puntuacion_normal", 8);
        ejercicio20.put("puntuacion_dificil", 12);
        ejercicio20.put("tipo", "pierna");
        ejercicio20.put("imagen_url", "escaladores");
        ejercicio20.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[19] = ejercicio20;

        Map<String, Object> ejercicio21 = new HashMap<>();
        ejercicio21.put("nombre", "Flexiones");
        ejercicio21.put("descripcion", "Ejercicio clásico para fortalecer el pecho.");
        ejercicio21.put("dificultad_facil", "10");
        ejercicio21.put("dificultad_normal", "15");
        ejercicio21.put("dificultad_dificil", "20");
        ejercicio21.put("medida","reps");
        ejercicio21.put("puntuacion_facil", 5);
        ejercicio21.put("puntuacion_normal", 10);
        ejercicio21.put("puntuacion_dificil", 15);
        ejercicio21.put("tipo", "pecho");
        ejercicio21.put("imagen_url", "flexiones");
        ejercicio21.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[20] = ejercicio21;

        Map<String, Object> ejercicio22 = new HashMap<>();
        ejercicio22.put("nombre", "Flexiones declinadas");
        ejercicio22.put("descripcion", "Con pies elevados, trabaja pecho superior.");
        ejercicio22.put("dificultad_facil", "8");
        ejercicio22.put("dificultad_normal", "12");
        ejercicio22.put("dificultad_dificil", "16");
        ejercicio22.put("medida","reps");
        ejercicio22.put("puntuacion_facil", 6);
        ejercicio22.put("puntuacion_normal", 12);
        ejercicio22.put("puntuacion_dificil", 18);
        ejercicio22.put("tipo", "pecho");
        ejercicio22.put("imagen_url", "flexiones_declinadas");
        ejercicio22.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[21] = ejercicio22;

        Map<String, Object> ejercicio23 = new HashMap<>();
        ejercicio23.put("nombre", "Press de banca");
        ejercicio23.put("descripcion", "Con barra, empuja desde el pecho.");
        ejercicio23.put("dificultad_facil", "8");
        ejercicio23.put("dificultad_normal", "12");
        ejercicio23.put("dificultad_dificil", "15");
        ejercicio23.put("medida","reps");
        ejercicio23.put("puntuacion_facil", 6);
        ejercicio23.put("puntuacion_normal", 12);
        ejercicio23.put("puntuacion_dificil", 18);
        ejercicio23.put("tipo", "pecho");
        ejercicio23.put("imagen_url", "press_banca");
        ejercicio23.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[22] = ejercicio23;

        Map<String, Object> ejercicio24 = new HashMap<>();
        ejercicio24.put("nombre", "Aperturas con mancuernas");
        ejercicio24.put("descripcion", "Abre y cierra los brazos acostado.");
        ejercicio24.put("dificultad_facil", "10");
        ejercicio24.put("dificultad_normal", "15");
        ejercicio24.put("dificultad_dificil", "20");
        ejercicio24.put("medida","reps");
        ejercicio24.put("puntuacion_facil", 5);
        ejercicio24.put("puntuacion_normal", 10);
        ejercicio24.put("puntuacion_dificil", 15);
        ejercicio24.put("tipo", "pecho");
        ejercicio24.put("imagen_url", "aperturas");
        ejercicio24.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[23] = ejercicio24;

        Map<String, Object> ejercicio25 = new HashMap<>();
        ejercicio25.put("nombre", "Push-up explosivo");
        ejercicio25.put("descripcion", "Empuja con fuerza para despegar manos.");
        ejercicio25.put("dificultad_facil", "8");
        ejercicio25.put("dificultad_normal", "12");
        ejercicio25.put("dificultad_dificil", "15");
        ejercicio25.put("medida","reps");
        ejercicio25.put("puntuacion_facil", 6);
        ejercicio25.put("puntuacion_normal", 12);
        ejercicio25.put("puntuacion_dificil", 18);
        ejercicio25.put("tipo", "pecho");
        ejercicio25.put("imagen_url", "flexiones");
        ejercicio25.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[24] = ejercicio25;

        Map<String, Object> ejercicio26 = new HashMap<>();
        ejercicio26.put("nombre", "Flexiones inclinadas");
        ejercicio26.put("descripcion", "Apoya manos en una superficie elevada.");
        ejercicio26.put("dificultad_facil", "10");
        ejercicio26.put("dificultad_normal", "15");
        ejercicio26.put("dificultad_dificil", "20");
        ejercicio26.put("medida","reps");
        ejercicio26.put("puntuacion_facil", 5);
        ejercicio26.put("puntuacion_normal", 10);
        ejercicio26.put("puntuacion_dificil", 15);
        ejercicio26.put("tipo", "pecho");
        ejercicio26.put("imagen_url", "flex_inclinadas");
        ejercicio26.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[25] = ejercicio26;

        Map<String, Object> ejercicio27 = new HashMap<>();
        ejercicio27.put("nombre", "Cruce de cables");
        ejercicio27.put("descripcion", "Ejercicio en poleas para pectorales.");
        ejercicio27.put("dificultad_facil", "10");
        ejercicio27.put("dificultad_normal", "15");
        ejercicio27.put("dificultad_dificil", "20");
        ejercicio27.put("medida","reps");
        ejercicio27.put("puntuacion_facil", 6);
        ejercicio27.put("puntuacion_normal", 12);
        ejercicio27.put("puntuacion_dificil", 18);
        ejercicio27.put("tipo", "pecho");
        ejercicio27.put("imagen_url", "cruce_cables");
        ejercicio27.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[26] = ejercicio27;

        Map<String, Object> ejercicio28 = new HashMap<>();
        ejercicio28.put("nombre", "Dips en paralelas");
        ejercicio28.put("descripcion", "Ejercicio de peso corporal para pecho y tríceps.");
        ejercicio28.put("dificultad_facil", "8");
        ejercicio28.put("dificultad_normal", "12");
        ejercicio28.put("dificultad_dificil", "15");
        ejercicio28.put("medida","reps");
        ejercicio28.put("puntuacion_facil", 6);
        ejercicio28.put("puntuacion_normal", 12);
        ejercicio28.put("puntuacion_dificil", 18);
        ejercicio28.put("tipo", "pecho");
        ejercicio28.put("imagen_url", "dips");
        ejercicio28.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[27] = ejercicio28;

        Map<String, Object> ejercicio29 = new HashMap<>();
        ejercicio29.put("nombre", "Press inclinado");
        ejercicio29.put("descripcion", "Trabaja parte superior del pecho.");
        ejercicio29.put("dificultad_facil", "8");
        ejercicio29.put("dificultad_normal", "12");
        ejercicio29.put("dificultad_dificil", "15");
        ejercicio29.put("medida","reps");
        ejercicio29.put("puntuacion_facil", 6);
        ejercicio29.put("puntuacion_normal", 12);
        ejercicio29.put("puntuacion_dificil", 18);
        ejercicio29.put("tipo", "pecho");
        ejercicio29.put("imagen_url", "press_inclinado");
        ejercicio29.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[28] = ejercicio29;

        Map<String, Object> ejercicio30 = new HashMap<>();
        ejercicio30.put("nombre", "Flexión con palmada");
        ejercicio30.put("descripcion", "Flexiones explosivas con palmada al subir.");
        ejercicio30.put("dificultad_facil", "8");
        ejercicio30.put("dificultad_normal", "12");
        ejercicio30.put("dificultad_dificil", "15");
        ejercicio30.put("medida","reps");
        ejercicio30.put("puntuacion_facil", 6);
        ejercicio30.put("puntuacion_normal", 12);
        ejercicio30.put("puntuacion_dificil", 18);
        ejercicio30.put("tipo", "pecho");
        ejercicio30.put("imagen_url", "flexiones");
        ejercicio30.put("video", "https://www.youtube.com/watch?v=XXXXXXX");
        ejercicios[29] = ejercicio30;

        return ejercicios;
    }
}
